### ISSUE TITLE
AssemblyScript runtime functions appear to be included twice in 2.8.0 which breaks compilation

### ISSUE THREAD

**Issue by jeffcharles** [jtenner/as-pect#195]
Given a test that looks like the following:

```typescript
describe("run", () => {
  it("Should verify something", () => {
    expect<i32>(2).toBe(2, "All good");
  });
});
```

I get output that looks like:
```
> jan20@1.0.0 test /Users/jeffreycharles/scripts/jan20
> asp --config test/as-pect.config.js

       ___   _____                       __    
      /   | / ___/      ____  ___  _____/ /_   
     / /| | \__ \______/ __ \/ _ \/ ___/ __/   
    / ___ |___/ /_____/ /_/ /  __/ /__/ /_     
   /_/  |_/____/     / .___/\___/\___/\__/     
                    /_/                        

⚡AS-pect⚡ Test suite runner [2.8.0]

[Log] Loading asc compiler
[Log] Compiler loaded in 346.183ms.
[Log] Using configuration /Users/jeffreycharles/scripts/jan20/test/as-pect.config.js
[Log] Using SummaryReporter
[Log] Including files: **/*.spec.ts
[Log] Running tests that match: (:?)
[Log] Running groups that match: (:?)
[Log] Effective command line args:
  [TestFile.ts] node_modules/@as-pect/assembly/assembly/index.ts --runtime stub --validate --debug --binaryFile output.wasm --explicitStart --use ASC_RTRACE=1 --importMemory

ERROR TS2300: Duplicate identifier '__visit'.

 function __visit(ref: usize, cookie: i32): void {
          ~~~~~~~
 in ~lib/rt/pure.ts(66,9)

 function __visit(ref: usize, cookie: u32): void {
          ~~~~~~~
 in ~lib/rt/stub.ts(97,9)

ERROR TS2300: Duplicate identifier '__collect'.

 export function __collect(): void {
                 ~~~~~~~~~
 in ~lib/rt/pure.ts(177,16)

 export function __collect(): void {
                 ~~~~~~~~~
 in ~lib/rt/stub.ts(102,16)

ERROR TS2300: Duplicate identifier '__retain'.

 export function __retain(ref: usize): usize {
                 ~~~~~~~~
 in ~lib/rt/pure.ts(253,16)

 export function __retain(ref: usize): usize {
                 ~~~~~~~~
 in ~lib/rt/stub.ts(86,16)

ERROR TS2300: Duplicate identifier '__release'.

 export function __release(ref: usize): void {
                 ~~~~~~~~~
 in ~lib/rt/pure.ts(260,16)

 export function __release(ref: usize): void {
                 ~~~~~~~~~
 in ~lib/rt/stub.ts(92,16)

ERROR TS2300: Duplicate identifier '__reset'.

 export function __reset(): void {
                 ~~~~~~~
 in ~lib/rt/pure.ts(266,16)

 export function __reset(): void { // special
                 ~~~~~~~
 in ~lib/rt/stub.ts(80,16)

ERROR TS2300: Duplicate identifier '__alloc'.

 export function __alloc(size: usize, id: u32): usize {
                 ~~~~~~~
 in ~lib/rt/tlsf.ts(571,16)

 export function __alloc(size: usize, id: u32): usize {
                 ~~~~~~~
 in ~lib/rt/stub.ts(27,16)

ERROR TS2300: Duplicate identifier '__realloc'.

 export function __realloc(ref: usize, size: usize): usize {
                 ~~~~~~~~~
 in ~lib/rt/tlsf.ts(584,16)

 export function __realloc(ptr: usize, size: usize): usize {
                 ~~~~~~~~~
 in ~lib/rt/stub.ts(42,16)

ERROR TS2300: Duplicate identifier '__free'.

 export function __free(ref: usize): void {
                 ~~~~~~
 in ~lib/rt/tlsf.ts(592,16)

 export function __free(ptr: usize): void {
                 ~~~~~~
 in ~lib/rt/stub.ts(69,16)

[Error] There was a compilation error when trying to create the wasm binary for file: test/jan20.spec.ts.
Error: Compile error
    at Object.main (/Users/jeffreycharles/scripts/jan20/node_modules/assemblyscript/cli/asc.js:558:21)
    at /Users/jeffreycharles/scripts/jan20/node_modules/@as-pect/cli/lib/run.js:433:21
    at Array.forEach (<anonymous>)
    at run (/Users/jeffreycharles/scripts/jan20/node_modules/@as-pect/cli/lib/run.js:431:40)
    at Object.asp (/Users/jeffreycharles/scripts/jan20/node_modules/@as-pect/cli/lib/index.js:72:13)
    at Object.<anonymous> (/Users/jeffreycharles/scripts/jan20/node_modules/@as-pect/cli/bin/asp:2:28)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
npm ERR! Test failed.  See above for more details.
```

after updating from 2.7.0 to 2.8.0. (2.7.0 compiled and ran the test successfully)

**Comment by willemneal** [comment]
This is related to #194 and will be fixed by #196
